### ISSUE TITLE
找了好久 终于找到了 有没有文档

### ISSUE THREAD

**Issue by OxYancy** [baiwumm/Xmw-Admin#1]
找了好久 终于找到了 有没有文档

**Comment by OxYancy** [comment]
部署起了 没有权限

**Comment by baiwumm** [comment]
兄弟，我当学习用的，我只开发了一半，把登录鉴权和动态菜单这块搞好而已，技术栈用的 Nest + React ，全部开发好我会部署，但还要一段时间，最近比较忙

**Comment by YanngGer** [comment]
@Cyan-Xmw 大佬可以分享一下数据库的初始化内容脚本吗？我这边后端跑起来了，只有表结构，没有内容，看不到前端页面的设计

**Comment by baiwumm** [comment]
> @Cyan-Xmw 大佬可以分享一下数据库的初始化内容脚本吗？我这边后端跑起来了，只有表结构，没有内容，看不到前端页面的设计

没有 sql 脚本，需要的话，可以导出一份数据库给你，加QQ: 843348394

**Comment by skylingfly** [comment]
> 兄弟，我当学习用的，我只开发了一半，把登录鉴权和动态菜单这块搞好而已，技术栈用的 Nest + React ，全部开发好我会部署，但还要一段时间，最近比较忙

big brother, 很棒的项目啥时候搞好啊 react Ts + Nest  正好可以好好学习借鉴，大大点赞
