### ISSUE TITLE
前端国际化怎么配置的啊

### ISSUE THREAD

**Issue by RichardZhang12** [baiwumm/Xmw-Admin#2]
前端国际化怎么配置的啊，我看local文件夹下没有配置变量，页面内文字变量如何替换

**Comment by baiwumm** [comment]
> 前端国际化怎么配置的啊，我看local文件夹下没有配置变量，页面内文字变量如何替换

国际化的字段是由接口返回的，local文件夹下的空文件只是让 Umi 能识别几种语言
