### ISSUE TITLE
国际化没有的问题

### ISSUE THREAD

**Issue by sunshinego12138** [baiwumm/Xmw-Admin#3]
国际化没有存到前端，而是后端传过来的

来自于`xmw_international`这张表

但是并没有提供这张表的sql，导致代码拉取下来运行后，国际化是空的

<img width="608" alt="image" src="https://github.com/baiwumm/Xmw-Admin/assets/56506553/2aab6df8-c8ff-466a-b5c1-955a12623bae">

大佬，要不补一下`xmw_international`这张表的sql

**Comment by baiwumm** [comment]
> 国际化没有存到前端，而是后端传过来的
> 
> 来自于`xmw_international`这张表
> 
> 但是并没有提供这张表的sql，导致代码拉取下来运行后，国际化是空的
> 
> <img alt="image" width="608" src="https://private-user-images.githubusercontent.com/56506553/312075480-2aab6df8-c8ff-466a-b5c1-955a12623bae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTM0NDAsIm5iZiI6MTcxMDI5MzE0MCwicGF0aCI6Ii81NjUwNjU1My8zMTIwNzU0ODAtMmFhYjZkZjgtYzhmZi00NjZhLWI1YzEtOTU1YTEyNjIzYmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAxMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjNkMDM5MmU0ZjAzNWQ5MWRmYWFkYjZhNzExMjUxM2RlYzA5NjhkNDkxYThmNWYyZjJiZjdjMTE3MmQyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMpGuAHcQcjP1WWvaeiIttxA9yPV0VnMtH59lul0bXw">
> 大佬，要不补一下`xmw_international`这张表的sql

https://baiwumm.com/p/8lkgmd0p

文章底部有 sql 链接，需要的可以自行下载
