### ISSUE TITLE
本地跑起来出现数据库错误

### ISSUE THREAD

**Issue by JeromeD3** [baiwumm/Xmw-Admin#4]
![image](https://github.com/baiwumm/Xmw-Admin/assets/67688096/8fa4a358-67f3-4ae2-a617-ef650c5d7640)

**Comment by JeromeD3** [comment]
错误位置为announcement.service 中`case when a.user_id = '${user_id}' then 1 else 0 end`,  将a改成u即可

**Comment by Damoness** [comment]
数据怎么来的
